#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include "enum_and_typedefs.h"
#include "io/io.h"
#include "r_operators/r_operators.h"
#include "diagnostics/diagnostics.h"
#include "time_stepping/time_stepping.h"
