int grad(Scalar_field, Vector_field, Grid *);
int laplace(Scalar_field, Scalar_field, Grid *);
int laplace_vec(Vector_field, Vector_field, Grid *, Dualgrid *);
int curl(Vector_field, Dual_vector_field, Grid *, Dualgrid *);
int curl_dual(Dual_vector_field, Vector_field, Grid *, Dualgrid *);
int cross_product(Vector_field, Dual_vector_field, Vector_field, Grid *);
int inner(Vector_field, Vector_field,Scalar_field, Grid *);
int divergence(Vector_field, Scalar_field, Grid *);
int recov_hor_par_dual(Dual_vector_field, long, long, double *, Grid *);
int recov_hor_par_pri(Vector_field, long, long, double *, Grid *);
int recov_hor_ver_dual(Dual_vector_field, long, long, double *, Grid *);
int recov_hor_ver_pri(Vector_field, long, long, double *, Grid *);
int recov_ver_0_dual(Dual_vector_field, long, long, double *, Grid *);
int recov_ver_0_pri(Vector_field, long, long, double *, Grid *);
int recov_ver_1_dual(Dual_vector_field, long, long, double *, Grid *);
int recov_ver_1_pri(Vector_field, long, long, double *, Grid *);
int tendency(State *, State *, Grid *, Dualgrid*, short);
int scalar_times_vector(Scalar_field, Vector_field, Vector_field, Grid *);
int linear_combine_two_states(State *, State *, State *, double, double);
