void adv_s(Vector_field, Scalar_field, Scalar_field);
void grad(Scalar_field, Vector_field);
void laplace(Scalar_field, Scalar_field);
void laplace_vec(Vector_field, Vector_field);
void rot(Vector_field, Dual_vector_field);
void rot_dual(Dual_vector_field, Vector_field);
void vector_product(Vector_field, Dual_vector_field, Vector_field);
void scalar_product(Vector_field, Vector_field,Scalar_field);
void divergence(Vector_field, Scalar_field);
void recov_hor_par_dual(Dual_vector_field, double[]);
void recov_hor_par_pri(Vector_field, double out_field[]);
void recov_hor_ver_dual(Dual_vector_field, double[]);
void recov_hor_ver_pri(Vector_field, double[]);
void recov_ver_1_dual(Dual_vector_field, double[]);
void recov_ver_1_pri(Vector_field, double[]);
void recov_ver_2_dual(Dual_vector_field, double[]);
void recov_ver_2_pri(Vector_field, double[]);
State tendency(State);
