#include <stdio.h>
#include <math.h>
#include <string.h>
#include "enum_and_typedefs.h"
#include "io/io.h"
#include "r_operators/r_operators.h"
#include "diagnostics/diagnostics.h"
#include "time_stepping/time_stepping.h"
Grid grid;
Dualgrid dualgrid;
#include "constants.h"
